--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/RajadorDev/AntiVPN
build-by-default: true
branches:
- main
projects:
  AntiVPN-WINHEBEGR:
    path: ""
    libs:
      - src: SOF3/await-generator/await-generator
        version: ^3.6.1
...

